# Generated by Django 5.1.4 on 2024-12-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="auther",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
